### PR TITLE
chore: update to nx 16

### PR DESCRIPTION
**Pull request by Cammisuli**

### CODE REVIEW

**Comment by fivehanz** [comment]
Hiya mate! 

Any possibilities of ETA of when nx16 support will be merged?

Thanks,
Hanz

**Comment by Cammisuli** [comment]
Oh I didnt put too much effort into it because we use `@monodon/rust` in the main nx repo without having this be updated to nx 16.

Is there a particular reason why you need this to be nx 16?

**Comment by fivehanz** [comment]
Ohh right, i did not realize i could use it right away!

I used it just sometime ago to create cloudflare worker and everything worked just fine, thanks!

I presumed it does not work with nx 16 currently because of this PR, and since the other `@nxrs/cargo` is not updated.

**Comment by Cammisuli** [comment]
ok cool! The main reason for this PR was just to make sure that the nx16 migration was working properly 😄

**Pull request merged**
